import AuthGuard from '@/components/auth/AuthGurard';
import useAuthQuery from '@/hooks/useAuthQuery';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function VerifyLayout({ children }: { children: React.ReactNode }) {
  // const data = useAuthQuery();

  // console.log("DATA : ", data);

  return (
    // <AuthGuard>
    <div className="w-full min-h-screen flex justify-center items-center">
      {children}
    </div>
    // </AuthGuard>
  );
}

export default VerifyLayout;
