import type { Metadata } from 'next';
import { Inter, Bricolage_Grotesque, Space_Grotesk } from 'next/font/google';
import '../globals.css';
import { cn } from '@/lib/utils';
import { TooltipProvider } from '@/components/ui/tooltip';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const SpaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
});

const BricolageGrotesque = Bricolage_Grotesque({
  variable: '--font-bricolage-grotesque',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { AppSidebar } from '@/components/app-sidebar';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { Toaster } from 'sonner';
import AuthGuard from '@/components/auth/AuthGurard';
import PrivateRouteAuthGuard from '@/components/auth/PrivateRouteAuthGuard';
import Header from '@/components/Header';

export default function PrivateRouteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <PrivateRouteAuthGuard>
          <div className="w-full h-full px-4 pb-2">{children}</div>
        </PrivateRouteAuthGuard>
        <Toaster />
      </SidebarInset>
    </SidebarProvider>
  );
}
